name: "Terraform Predictive Plan"

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write  # Allows posting PR comments
  id-token: write
  contents: read

jobs:
  terraform-predictive-plan:
    name: "Terraform Predictive Plan"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure environment variables
        run: |
          echo "AVIATRIX_CONTROLLER_IP=${{ secrets.AVIATRIX_CONTROLLER_IP }}" >> $GITHUB_ENV
          echo "AVIATRIX_USERNAME=${{ secrets.AVIATRIX_USERNAME }}" >> $GITHUB_ENV
          echo "AVIATRIX_PASSWORD=${{ secrets.AVIATRIX_PASSWORD }}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: terraform plan -out=tfplan

      - name: Show Human-Readable Terraform Plan
        run: terraform show -no-color tfplan | tee tfplan.txt

      - name: Post Plan as PR Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('tfplan.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terraform Plan Output :construction:
              
              \`\`\`
              ${plan.substring(0, 6000)}
              \`\`\`
              
              *(Note: Truncated if too long. Check logs for full plan.)*`
            });